apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: weather-frontend
  template:
    metadata:
      labels:
        app: weather-frontend
    spec:
      containers:
        - name: weather-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: 5001
          env:
            - name: BACKEND_URL
              # זהו שם ה-Service שייצרנו (או נייצר תיכף)
              value: "http://weather-backend-svc:5000"