# Service עבור ה-Backend
apiVersion: v1
kind: Service
metadata:
  name: weather-backend-svc
spec:
  type: ClusterIP # גישה פנימית בלבד בתוך הקלאסטר
  selector:
    app: weather-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
# Service עבור ה-Frontend
apiVersion: v1
kind: Service
metadata:
  name: weather-frontend-svc
spec:
  type: NodePort # מאפשר לנו לגשת לאפליקציה מבחוץ (דרך Minikube)
  selector:
    app: weather-frontend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30001 # פורט קבוע שתוכל להקיש בדפדפן