global:
  environment: dev

backend:
  replicaCount: 1
  image:
    tag: "13f76ce2b9ef7da6c6465d5ec3dfe12f3348fcde"

frontend:
  replicaCount: 1
  image:
    tag: "initial"

tracker:
  image:
    tag: "afd77b4d673029c7a4eb51ba8b73673c0c13233d"