global:
  environment: dev

backend:
  replicaCount: 1
  image:
    tag: "initial"

frontend:
  replicaCount: 1
  image:
    tag: "initial"

tracker:
  image:
    tag: "afd77b4d673029c7a4eb51ba8b73673c0c13233d"